/// 16.10.48 Status downlink (also B.3.10 Status downlink in ETSI EN 300 396-5, Gateway air interface)
/// Bits: 6
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(u8)]
pub enum StatusDownlink {
    ChangeOfEnergySavingModeRequest = 1,
    ChangeOfEnergySavingModeResponse = 2,
    DualWatchModeResponse = 3,
    TerminatingDualWatchModeResponse = 4,
    ChangeOfDualWatchModeRequest = 5,
    MsFrequencyBandsRequest = 7,
    PeriodicDistanceReporting = 8,
    AcceptanceToStartDmGatewayOperation = 16,
    RejectionToStartDmGatewayOperation = 17,
    AcceptanceToContinueDmGatewayOperation = 18,
    RejectionToContinueDmGatewayOperation = 19,
    AcceptanceToStopDmGatewayOperation = 20,
    AcceptanceOfDmMsAddresses = 21,
    CommandToRemoveDmMsAddresses = 22,
    CommandToChangeRegistrationLabel = 23,
    CommandToStopDmGatewayOperation = 24,
    NetworkOrUserSpecific32 = 32,
    NetworkOrUserSpecific33 = 33,
    NetworkOrUserSpecific34 = 34,
    NetworkOrUserSpecific35 = 35,
    NetworkOrUserSpecific36 = 36,
    NetworkOrUserSpecific37 = 37,
    NetworkOrUserSpecific38 = 38,
    NetworkOrUserSpecific39 = 39,
    NetworkOrUserSpecific40 = 40,
    NetworkOrUserSpecific41 = 41,
    NetworkOrUserSpecific42 = 42,
    NetworkOrUserSpecific43 = 43,
    NetworkOrUserSpecific44 = 44,
    NetworkOrUserSpecific45 = 45,
    NetworkOrUserSpecific46 = 46,
    NetworkOrUserSpecific47 = 47,
    NetworkOrUserSpecific48 = 48,
    NetworkOrUserSpecific49 = 49,
    NetworkOrUserSpecific50 = 50,
    NetworkOrUserSpecific51 = 51,
    NetworkOrUserSpecific52 = 52,
    NetworkOrUserSpecific53 = 53,
    NetworkOrUserSpecific54 = 54,
    NetworkOrUserSpecific55 = 55,
    NetworkOrUserSpecific56 = 56,
    NetworkOrUserSpecific57 = 57,
    NetworkOrUserSpecific58 = 58,
    NetworkOrUserSpecific59 = 59,
    NetworkOrUserSpecific60 = 60,
    NetworkOrUserSpecific61 = 61,
    NetworkOrUserSpecific62 = 62,
    NetworkOrUserSpecific63 = 63,
}

impl std::convert::TryFrom<u64> for StatusDownlink {
    type Error = ();
    fn try_from(x: u64) -> Result<Self, Self::Error> {
        match x {
            1 => Ok(StatusDownlink::ChangeOfEnergySavingModeRequest),
            2 => Ok(StatusDownlink::ChangeOfEnergySavingModeResponse),
            3 => Ok(StatusDownlink::DualWatchModeResponse),
            4 => Ok(StatusDownlink::TerminatingDualWatchModeResponse),
            5 => Ok(StatusDownlink::ChangeOfDualWatchModeRequest),
            7 => Ok(StatusDownlink::MsFrequencyBandsRequest),
            8 => Ok(StatusDownlink::PeriodicDistanceReporting),
            16 => Ok(StatusDownlink::AcceptanceToStartDmGatewayOperation),
            17 => Ok(StatusDownlink::RejectionToStartDmGatewayOperation),
            18 => Ok(StatusDownlink::AcceptanceToContinueDmGatewayOperation),
            19 => Ok(StatusDownlink::RejectionToContinueDmGatewayOperation),
            20 => Ok(StatusDownlink::AcceptanceToStopDmGatewayOperation),
            21 => Ok(StatusDownlink::AcceptanceOfDmMsAddresses),
            22 => Ok(StatusDownlink::CommandToRemoveDmMsAddresses),
            23 => Ok(StatusDownlink::CommandToChangeRegistrationLabel),
            24 => Ok(StatusDownlink::CommandToStopDmGatewayOperation),
            32 => Ok(StatusDownlink::NetworkOrUserSpecific32),
            33 => Ok(StatusDownlink::NetworkOrUserSpecific33),
            34 => Ok(StatusDownlink::NetworkOrUserSpecific34),
            35 => Ok(StatusDownlink::NetworkOrUserSpecific35),
            36 => Ok(StatusDownlink::NetworkOrUserSpecific36),
            37 => Ok(StatusDownlink::NetworkOrUserSpecific37),
            38 => Ok(StatusDownlink::NetworkOrUserSpecific38),
            39 => Ok(StatusDownlink::NetworkOrUserSpecific39),
            40 => Ok(StatusDownlink::NetworkOrUserSpecific40),
            41 => Ok(StatusDownlink::NetworkOrUserSpecific41),
            42 => Ok(StatusDownlink::NetworkOrUserSpecific42),
            43 => Ok(StatusDownlink::NetworkOrUserSpecific43),
            44 => Ok(StatusDownlink::NetworkOrUserSpecific44),
            45 => Ok(StatusDownlink::NetworkOrUserSpecific45),
            46 => Ok(StatusDownlink::NetworkOrUserSpecific46),
            47 => Ok(StatusDownlink::NetworkOrUserSpecific47),
            48 => Ok(StatusDownlink::NetworkOrUserSpecific48),
            49 => Ok(StatusDownlink::NetworkOrUserSpecific49),
            50 => Ok(StatusDownlink::NetworkOrUserSpecific50),
            51 => Ok(StatusDownlink::NetworkOrUserSpecific51),
            52 => Ok(StatusDownlink::NetworkOrUserSpecific52),
            53 => Ok(StatusDownlink::NetworkOrUserSpecific53),
            54 => Ok(StatusDownlink::NetworkOrUserSpecific54),
            55 => Ok(StatusDownlink::NetworkOrUserSpecific55),
            56 => Ok(StatusDownlink::NetworkOrUserSpecific56),
            57 => Ok(StatusDownlink::NetworkOrUserSpecific57),
            58 => Ok(StatusDownlink::NetworkOrUserSpecific58),
            59 => Ok(StatusDownlink::NetworkOrUserSpecific59),
            60 => Ok(StatusDownlink::NetworkOrUserSpecific60),
            61 => Ok(StatusDownlink::NetworkOrUserSpecific61),
            62 => Ok(StatusDownlink::NetworkOrUserSpecific62),
            63 => Ok(StatusDownlink::NetworkOrUserSpecific63),
            _ => Err(()),
        }
    }
}

impl StatusDownlink {
    /// Convert this enum back into the raw integer value
    pub fn into_raw(self) -> u64 {
        match self {
            StatusDownlink::ChangeOfEnergySavingModeRequest => 1,
            StatusDownlink::ChangeOfEnergySavingModeResponse => 2,
            StatusDownlink::DualWatchModeResponse => 3,
            StatusDownlink::TerminatingDualWatchModeResponse => 4,
            StatusDownlink::ChangeOfDualWatchModeRequest => 5,
            StatusDownlink::MsFrequencyBandsRequest => 7,
            StatusDownlink::PeriodicDistanceReporting => 8,
            StatusDownlink::AcceptanceToStartDmGatewayOperation => 16,
            StatusDownlink::RejectionToStartDmGatewayOperation => 17,
            StatusDownlink::AcceptanceToContinueDmGatewayOperation => 18,
            StatusDownlink::RejectionToContinueDmGatewayOperation => 19,
            StatusDownlink::AcceptanceToStopDmGatewayOperation => 20,
            StatusDownlink::AcceptanceOfDmMsAddresses => 21,
            StatusDownlink::CommandToRemoveDmMsAddresses => 22,
            StatusDownlink::CommandToChangeRegistrationLabel => 23,
            StatusDownlink::CommandToStopDmGatewayOperation => 24,
            StatusDownlink::NetworkOrUserSpecific32 => 32,
            StatusDownlink::NetworkOrUserSpecific33 => 33,
            StatusDownlink::NetworkOrUserSpecific34 => 34,
            StatusDownlink::NetworkOrUserSpecific35 => 35,
            StatusDownlink::NetworkOrUserSpecific36 => 36,
            StatusDownlink::NetworkOrUserSpecific37 => 37,
            StatusDownlink::NetworkOrUserSpecific38 => 38,
            StatusDownlink::NetworkOrUserSpecific39 => 39,
            StatusDownlink::NetworkOrUserSpecific40 => 40,
            StatusDownlink::NetworkOrUserSpecific41 => 41,
            StatusDownlink::NetworkOrUserSpecific42 => 42,
            StatusDownlink::NetworkOrUserSpecific43 => 43,
            StatusDownlink::NetworkOrUserSpecific44 => 44,
            StatusDownlink::NetworkOrUserSpecific45 => 45,
            StatusDownlink::NetworkOrUserSpecific46 => 46,
            StatusDownlink::NetworkOrUserSpecific47 => 47,
            StatusDownlink::NetworkOrUserSpecific48 => 48,
            StatusDownlink::NetworkOrUserSpecific49 => 49,
            StatusDownlink::NetworkOrUserSpecific50 => 50,
            StatusDownlink::NetworkOrUserSpecific51 => 51,
            StatusDownlink::NetworkOrUserSpecific52 => 52,
            StatusDownlink::NetworkOrUserSpecific53 => 53,
            StatusDownlink::NetworkOrUserSpecific54 => 54,
            StatusDownlink::NetworkOrUserSpecific55 => 55,
            StatusDownlink::NetworkOrUserSpecific56 => 56,
            StatusDownlink::NetworkOrUserSpecific57 => 57,
            StatusDownlink::NetworkOrUserSpecific58 => 58,
            StatusDownlink::NetworkOrUserSpecific59 => 59,
            StatusDownlink::NetworkOrUserSpecific60 => 60,
            StatusDownlink::NetworkOrUserSpecific61 => 61,
            StatusDownlink::NetworkOrUserSpecific62 => 62,
            StatusDownlink::NetworkOrUserSpecific63 => 63,
        }
    }
}

impl From<StatusDownlink> for u64 {
    fn from(e: StatusDownlink) -> Self { e.into_raw() }
}

impl core::fmt::Display for StatusDownlink {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        match self {
            StatusDownlink::ChangeOfEnergySavingModeRequest => write!(f, "ChangeOfEnergySavingModeRequest"),
            StatusDownlink::ChangeOfEnergySavingModeResponse => write!(f, "ChangeOfEnergySavingModeResponse"),
            StatusDownlink::DualWatchModeResponse => write!(f, "DualWatchModeResponse"),
            StatusDownlink::TerminatingDualWatchModeResponse => write!(f, "TerminatingDualWatchModeResponse"),
            StatusDownlink::ChangeOfDualWatchModeRequest => write!(f, "ChangeOfDualWatchModeRequest"),
            StatusDownlink::MsFrequencyBandsRequest => write!(f, "MsFrequencyBandsRequest"),
            StatusDownlink::PeriodicDistanceReporting => write!(f, "PeriodicDistanceReporting"),
            StatusDownlink::AcceptanceToStartDmGatewayOperation => write!(f, "AcceptanceToStartDmGatewayOperation"),
            StatusDownlink::RejectionToStartDmGatewayOperation => write!(f, "RejectionToStartDmGatewayOperation"),
            StatusDownlink::AcceptanceToContinueDmGatewayOperation => write!(f, "AcceptanceToContinueDmGatewayOperation"),
            StatusDownlink::RejectionToContinueDmGatewayOperation => write!(f, "RejectionToContinueDmGatewayOperation"),
            StatusDownlink::AcceptanceToStopDmGatewayOperation => write!(f, "AcceptanceToStopDmGatewayOperation"),
            StatusDownlink::AcceptanceOfDmMsAddresses => write!(f, "AcceptanceOfDmMsAddresses"),
            StatusDownlink::CommandToRemoveDmMsAddresses => write!(f, "CommandToRemoveDmMsAddresses"),
            StatusDownlink::CommandToChangeRegistrationLabel => write!(f, "CommandToChangeRegistrationLabel"),
            StatusDownlink::CommandToStopDmGatewayOperation => write!(f, "CommandToStopDmGatewayOperation"),
            StatusDownlink::NetworkOrUserSpecific32 => write!(f, "NetworkOrUserSpecific32"),
            StatusDownlink::NetworkOrUserSpecific33 => write!(f, "NetworkOrUserSpecific33"),
            StatusDownlink::NetworkOrUserSpecific34 => write!(f, "NetworkOrUserSpecific34"),
            StatusDownlink::NetworkOrUserSpecific35 => write!(f, "NetworkOrUserSpecific35"),
            StatusDownlink::NetworkOrUserSpecific36 => write!(f, "NetworkOrUserSpecific36"),
            StatusDownlink::NetworkOrUserSpecific37 => write!(f, "NetworkOrUserSpecific37"),
            StatusDownlink::NetworkOrUserSpecific38 => write!(f, "NetworkOrUserSpecific38"),
            StatusDownlink::NetworkOrUserSpecific39 => write!(f, "NetworkOrUserSpecific39"),
            StatusDownlink::NetworkOrUserSpecific40 => write!(f, "NetworkOrUserSpecific40"),
            StatusDownlink::NetworkOrUserSpecific41 => write!(f, "NetworkOrUserSpecific41"),
            StatusDownlink::NetworkOrUserSpecific42 => write!(f, "NetworkOrUserSpecific42"),
            StatusDownlink::NetworkOrUserSpecific43 => write!(f, "NetworkOrUserSpecific43"),
            StatusDownlink::NetworkOrUserSpecific44 => write!(f, "NetworkOrUserSpecific44"),
            StatusDownlink::NetworkOrUserSpecific45 => write!(f, "NetworkOrUserSpecific45"),
            StatusDownlink::NetworkOrUserSpecific46 => write!(f, "NetworkOrUserSpecific46"),
            StatusDownlink::NetworkOrUserSpecific47 => write!(f, "NetworkOrUserSpecific47"),
            StatusDownlink::NetworkOrUserSpecific48 => write!(f, "NetworkOrUserSpecific48"),
            StatusDownlink::NetworkOrUserSpecific49 => write!(f, "NetworkOrUserSpecific49"),
            StatusDownlink::NetworkOrUserSpecific50 => write!(f, "NetworkOrUserSpecific50"),
            StatusDownlink::NetworkOrUserSpecific51 => write!(f, "NetworkOrUserSpecific51"),
            StatusDownlink::NetworkOrUserSpecific52 => write!(f, "NetworkOrUserSpecific52"),
            StatusDownlink::NetworkOrUserSpecific53 => write!(f, "NetworkOrUserSpecific53"),
            StatusDownlink::NetworkOrUserSpecific54 => write!(f, "NetworkOrUserSpecific54"),
            StatusDownlink::NetworkOrUserSpecific55 => write!(f, "NetworkOrUserSpecific55"),
            StatusDownlink::NetworkOrUserSpecific56 => write!(f, "NetworkOrUserSpecific56"),
            StatusDownlink::NetworkOrUserSpecific57 => write!(f, "NetworkOrUserSpecific57"),
            StatusDownlink::NetworkOrUserSpecific58 => write!(f, "NetworkOrUserSpecific58"),
            StatusDownlink::NetworkOrUserSpecific59 => write!(f, "NetworkOrUserSpecific59"),
            StatusDownlink::NetworkOrUserSpecific60 => write!(f, "NetworkOrUserSpecific60"),
            StatusDownlink::NetworkOrUserSpecific61 => write!(f, "NetworkOrUserSpecific61"),
            StatusDownlink::NetworkOrUserSpecific62 => write!(f, "NetworkOrUserSpecific62"),
            StatusDownlink::NetworkOrUserSpecific63 => write!(f, "NetworkOrUserSpecific63"),
        }
    }
}
