/// 16.10.48a Status uplink (also B.3.11 Status uplink in ETSI EN 300 396-5, Gateway air interface)
/// Bits: 6
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(u8)]
pub enum StatusUplink {
    ChangeOfEnergySavingModeRequest = 1,
    ChangeOfEnergySavingModeResponse = 2,
    DualWatchModeRequest = 3,
    TerminatingDualWatchModeRequest = 4,
    ChangeOfDualWatchModeResponse = 5,
    StartOfDirectModeOperation = 6,
    MsFrequencyBandsInformation = 7,
    RequestToStartDmGatewayOperation = 16,
    RequestToContinuedmGatewayOperation = 17,
    RequestToStopDmGatewayOperation = 18,
    RequestToAddDmMsAddresses = 19,
    RequestToRemoveDmMsAddresses = 20,
    RequestToReplaceDmMsAddresses = 21,
    AcceptanceToRemovalOfDmMsAddresses = 22,
    AcceptanceToChangeRegistrationLabel = 23,
    AcceptanceToStopDmGatewayOperation = 24,
    NetworkOrUserSpecific32 = 32,
    NetworkOrUserSpecific33 = 33,
    NetworkOrUserSpecific34 = 34,
    NetworkOrUserSpecific35 = 35,
    NetworkOrUserSpecific36 = 36,
    NetworkOrUserSpecific37 = 37,
    NetworkOrUserSpecific38 = 38,
    NetworkOrUserSpecific39 = 39,
    NetworkOrUserSpecific40 = 40,
    NetworkOrUserSpecific41 = 41,
    NetworkOrUserSpecific42 = 42,
    NetworkOrUserSpecific43 = 43,
    NetworkOrUserSpecific44 = 44,
    NetworkOrUserSpecific45 = 45,
    NetworkOrUserSpecific46 = 46,
    NetworkOrUserSpecific47 = 47,
    NetworkOrUserSpecific48 = 48,
    NetworkOrUserSpecific49 = 49,
    NetworkOrUserSpecific50 = 50,
    NetworkOrUserSpecific51 = 51,
    NetworkOrUserSpecific52 = 52,
    NetworkOrUserSpecific53 = 53,
    NetworkOrUserSpecific54 = 54,
    NetworkOrUserSpecific55 = 55,
    NetworkOrUserSpecific56 = 56,
    NetworkOrUserSpecific57 = 57,
    NetworkOrUserSpecific58 = 58,
    NetworkOrUserSpecific59 = 59,
    NetworkOrUserSpecific60 = 60,
    NetworkOrUserSpecific61 = 61,
    NetworkOrUserSpecific62 = 62,
    NetworkOrUserSpecific63 = 63,
}

impl std::convert::TryFrom<u64> for StatusUplink {
    type Error = ();
    fn try_from(x: u64) -> Result<Self, Self::Error> {
        match x {
            1 => Ok(StatusUplink::ChangeOfEnergySavingModeRequest),
            2 => Ok(StatusUplink::ChangeOfEnergySavingModeResponse),
            3 => Ok(StatusUplink::DualWatchModeRequest),
            4 => Ok(StatusUplink::TerminatingDualWatchModeRequest),
            5 => Ok(StatusUplink::ChangeOfDualWatchModeResponse),
            6 => Ok(StatusUplink::StartOfDirectModeOperation),
            7 => Ok(StatusUplink::MsFrequencyBandsInformation),
            16 => Ok(StatusUplink::RequestToStartDmGatewayOperation),
            17 => Ok(StatusUplink::RequestToContinuedmGatewayOperation),
            18 => Ok(StatusUplink::RequestToStopDmGatewayOperation),
            19 => Ok(StatusUplink::RequestToAddDmMsAddresses),
            20 => Ok(StatusUplink::RequestToRemoveDmMsAddresses),
            21 => Ok(StatusUplink::RequestToReplaceDmMsAddresses),
            22 => Ok(StatusUplink::AcceptanceToRemovalOfDmMsAddresses),
            23 => Ok(StatusUplink::AcceptanceToChangeRegistrationLabel),
            24 => Ok(StatusUplink::AcceptanceToStopDmGatewayOperation),
            32 => Ok(StatusUplink::NetworkOrUserSpecific32),
            33 => Ok(StatusUplink::NetworkOrUserSpecific33),
            34 => Ok(StatusUplink::NetworkOrUserSpecific34),
            35 => Ok(StatusUplink::NetworkOrUserSpecific35),
            36 => Ok(StatusUplink::NetworkOrUserSpecific36),
            37 => Ok(StatusUplink::NetworkOrUserSpecific37),
            38 => Ok(StatusUplink::NetworkOrUserSpecific38),
            39 => Ok(StatusUplink::NetworkOrUserSpecific39),
            40 => Ok(StatusUplink::NetworkOrUserSpecific40),
            41 => Ok(StatusUplink::NetworkOrUserSpecific41),
            42 => Ok(StatusUplink::NetworkOrUserSpecific42),
            43 => Ok(StatusUplink::NetworkOrUserSpecific43),
            44 => Ok(StatusUplink::NetworkOrUserSpecific44),
            45 => Ok(StatusUplink::NetworkOrUserSpecific45),
            46 => Ok(StatusUplink::NetworkOrUserSpecific46),
            47 => Ok(StatusUplink::NetworkOrUserSpecific47),
            48 => Ok(StatusUplink::NetworkOrUserSpecific48),
            49 => Ok(StatusUplink::NetworkOrUserSpecific49),
            50 => Ok(StatusUplink::NetworkOrUserSpecific50),
            51 => Ok(StatusUplink::NetworkOrUserSpecific51),
            52 => Ok(StatusUplink::NetworkOrUserSpecific52),
            53 => Ok(StatusUplink::NetworkOrUserSpecific53),
            54 => Ok(StatusUplink::NetworkOrUserSpecific54),
            55 => Ok(StatusUplink::NetworkOrUserSpecific55),
            56 => Ok(StatusUplink::NetworkOrUserSpecific56),
            57 => Ok(StatusUplink::NetworkOrUserSpecific57),
            58 => Ok(StatusUplink::NetworkOrUserSpecific58),
            59 => Ok(StatusUplink::NetworkOrUserSpecific59),
            60 => Ok(StatusUplink::NetworkOrUserSpecific60),
            61 => Ok(StatusUplink::NetworkOrUserSpecific61),
            62 => Ok(StatusUplink::NetworkOrUserSpecific62),
            63 => Ok(StatusUplink::NetworkOrUserSpecific63),
            _ => Err(()),
        }
    }
}

impl StatusUplink {
    /// Convert this enum back into the raw integer value
    pub fn into_raw(self) -> u64 {
        match self {
            StatusUplink::ChangeOfEnergySavingModeRequest => 1,
            StatusUplink::ChangeOfEnergySavingModeResponse => 2,
            StatusUplink::DualWatchModeRequest => 3,
            StatusUplink::TerminatingDualWatchModeRequest => 4,
            StatusUplink::ChangeOfDualWatchModeResponse => 5,
            StatusUplink::StartOfDirectModeOperation => 6,
            StatusUplink::MsFrequencyBandsInformation => 7,
            StatusUplink::RequestToStartDmGatewayOperation => 16,
            StatusUplink::RequestToContinuedmGatewayOperation => 17,
            StatusUplink::RequestToStopDmGatewayOperation => 18,
            StatusUplink::RequestToAddDmMsAddresses => 19,
            StatusUplink::RequestToRemoveDmMsAddresses => 20,
            StatusUplink::RequestToReplaceDmMsAddresses => 21,
            StatusUplink::AcceptanceToRemovalOfDmMsAddresses => 22,
            StatusUplink::AcceptanceToChangeRegistrationLabel => 23,
            StatusUplink::AcceptanceToStopDmGatewayOperation => 24,
            StatusUplink::NetworkOrUserSpecific32 => 32,
            StatusUplink::NetworkOrUserSpecific33 => 33,
            StatusUplink::NetworkOrUserSpecific34 => 34,
            StatusUplink::NetworkOrUserSpecific35 => 35,
            StatusUplink::NetworkOrUserSpecific36 => 36,
            StatusUplink::NetworkOrUserSpecific37 => 37,
            StatusUplink::NetworkOrUserSpecific38 => 38,
            StatusUplink::NetworkOrUserSpecific39 => 39,
            StatusUplink::NetworkOrUserSpecific40 => 40,
            StatusUplink::NetworkOrUserSpecific41 => 41,
            StatusUplink::NetworkOrUserSpecific42 => 42,
            StatusUplink::NetworkOrUserSpecific43 => 43,
            StatusUplink::NetworkOrUserSpecific44 => 44,
            StatusUplink::NetworkOrUserSpecific45 => 45,
            StatusUplink::NetworkOrUserSpecific46 => 46,
            StatusUplink::NetworkOrUserSpecific47 => 47,
            StatusUplink::NetworkOrUserSpecific48 => 48,
            StatusUplink::NetworkOrUserSpecific49 => 49,
            StatusUplink::NetworkOrUserSpecific50 => 50,
            StatusUplink::NetworkOrUserSpecific51 => 51,
            StatusUplink::NetworkOrUserSpecific52 => 52,
            StatusUplink::NetworkOrUserSpecific53 => 53,
            StatusUplink::NetworkOrUserSpecific54 => 54,
            StatusUplink::NetworkOrUserSpecific55 => 55,
            StatusUplink::NetworkOrUserSpecific56 => 56,
            StatusUplink::NetworkOrUserSpecific57 => 57,
            StatusUplink::NetworkOrUserSpecific58 => 58,
            StatusUplink::NetworkOrUserSpecific59 => 59,
            StatusUplink::NetworkOrUserSpecific60 => 60,
            StatusUplink::NetworkOrUserSpecific61 => 61,
            StatusUplink::NetworkOrUserSpecific62 => 62,
            StatusUplink::NetworkOrUserSpecific63 => 63,
        }
    }
}

impl From<StatusUplink> for u64 {
    fn from(e: StatusUplink) -> Self { e.into_raw() }
}

impl core::fmt::Display for StatusUplink {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        match self {
            StatusUplink::ChangeOfEnergySavingModeRequest => write!(f, "ChangeOfEnergySavingModeRequest"),
            StatusUplink::ChangeOfEnergySavingModeResponse => write!(f, "ChangeOfEnergySavingModeResponse"),
            StatusUplink::DualWatchModeRequest => write!(f, "DualWatchModeRequest"),
            StatusUplink::TerminatingDualWatchModeRequest => write!(f, "TerminatingDualWatchModeRequest"),
            StatusUplink::ChangeOfDualWatchModeResponse => write!(f, "ChangeOfDualWatchModeResponse"),
            StatusUplink::StartOfDirectModeOperation => write!(f, "StartOfDirectModeOperation"),
            StatusUplink::MsFrequencyBandsInformation => write!(f, "MsFrequencyBandsInformation"),
            StatusUplink::RequestToStartDmGatewayOperation => write!(f, "RequestToStartDmGatewayOperation"),
            StatusUplink::RequestToContinuedmGatewayOperation => write!(f, "RequestToContinuedmGatewayOperation"),
            StatusUplink::RequestToStopDmGatewayOperation => write!(f, "RequestToStopDmGatewayOperation"),
            StatusUplink::RequestToAddDmMsAddresses => write!(f, "RequestToAddDmMsAddresses"),
            StatusUplink::RequestToRemoveDmMsAddresses => write!(f, "RequestToRemoveDmMsAddresses"),
            StatusUplink::RequestToReplaceDmMsAddresses => write!(f, "RequestToReplaceDmMsAddresses"),
            StatusUplink::AcceptanceToRemovalOfDmMsAddresses => write!(f, "AcceptanceToRemovalOfDmMsAddresses"),
            StatusUplink::AcceptanceToChangeRegistrationLabel => write!(f, "AcceptanceToChangeRegistrationLabel"),
            StatusUplink::AcceptanceToStopDmGatewayOperation => write!(f, "AcceptanceToStopDmGatewayOperation"),
            StatusUplink::NetworkOrUserSpecific32 => write!(f, "NetworkOrUserSpecific32"),
            StatusUplink::NetworkOrUserSpecific33 => write!(f, "NetworkOrUserSpecific33"),
            StatusUplink::NetworkOrUserSpecific34 => write!(f, "NetworkOrUserSpecific34"),
            StatusUplink::NetworkOrUserSpecific35 => write!(f, "NetworkOrUserSpecific35"),
            StatusUplink::NetworkOrUserSpecific36 => write!(f, "NetworkOrUserSpecific36"),
            StatusUplink::NetworkOrUserSpecific37 => write!(f, "NetworkOrUserSpecific37"),
            StatusUplink::NetworkOrUserSpecific38 => write!(f, "NetworkOrUserSpecific38"),
            StatusUplink::NetworkOrUserSpecific39 => write!(f, "NetworkOrUserSpecific39"),
            StatusUplink::NetworkOrUserSpecific40 => write!(f, "NetworkOrUserSpecific40"),
            StatusUplink::NetworkOrUserSpecific41 => write!(f, "NetworkOrUserSpecific41"),
            StatusUplink::NetworkOrUserSpecific42 => write!(f, "NetworkOrUserSpecific42"),
            StatusUplink::NetworkOrUserSpecific43 => write!(f, "NetworkOrUserSpecific43"),
            StatusUplink::NetworkOrUserSpecific44 => write!(f, "NetworkOrUserSpecific44"),
            StatusUplink::NetworkOrUserSpecific45 => write!(f, "NetworkOrUserSpecific45"),
            StatusUplink::NetworkOrUserSpecific46 => write!(f, "NetworkOrUserSpecific46"),
            StatusUplink::NetworkOrUserSpecific47 => write!(f, "NetworkOrUserSpecific47"),
            StatusUplink::NetworkOrUserSpecific48 => write!(f, "NetworkOrUserSpecific48"),
            StatusUplink::NetworkOrUserSpecific49 => write!(f, "NetworkOrUserSpecific49"),
            StatusUplink::NetworkOrUserSpecific50 => write!(f, "NetworkOrUserSpecific50"),
            StatusUplink::NetworkOrUserSpecific51 => write!(f, "NetworkOrUserSpecific51"),
            StatusUplink::NetworkOrUserSpecific52 => write!(f, "NetworkOrUserSpecific52"),
            StatusUplink::NetworkOrUserSpecific53 => write!(f, "NetworkOrUserSpecific53"),
            StatusUplink::NetworkOrUserSpecific54 => write!(f, "NetworkOrUserSpecific54"),
            StatusUplink::NetworkOrUserSpecific55 => write!(f, "NetworkOrUserSpecific55"),
            StatusUplink::NetworkOrUserSpecific56 => write!(f, "NetworkOrUserSpecific56"),
            StatusUplink::NetworkOrUserSpecific57 => write!(f, "NetworkOrUserSpecific57"),
            StatusUplink::NetworkOrUserSpecific58 => write!(f, "NetworkOrUserSpecific58"),
            StatusUplink::NetworkOrUserSpecific59 => write!(f, "NetworkOrUserSpecific59"),
            StatusUplink::NetworkOrUserSpecific60 => write!(f, "NetworkOrUserSpecific60"),
            StatusUplink::NetworkOrUserSpecific61 => write!(f, "NetworkOrUserSpecific61"),
            StatusUplink::NetworkOrUserSpecific62 => write!(f, "NetworkOrUserSpecific62"),
            StatusUplink::NetworkOrUserSpecific63 => write!(f, "NetworkOrUserSpecific63"),
        }
    }
}
